server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: SATELLITE-SERVICE
          uri: lb://SATELLITE-SERVICE
          predicates:
            - Path=/satellites/**
        - id : CONSTELLATION-SERVICE
          uri: lb://CONSTELLATION-SERVICE
          predicates:
            - Path=/constellations/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-registry:8761/eureka
#    instance:
#      hostname: localhost